### ISSUE TITLE
Nothing happens on new project

### ISSUE THREAD

**Issue by glensc** [tmdh/laravel-kit#11]
**Describe the bug**

Nothing happens on create new project

**To Reproduce**
1. Cmd+N (or from the menu)
2. Create new folder or navigate to empty folder

**Expected behavior**

Anything!

**Desktop**
 - OS: macOS
 - Laravel Kit version: installed from brew cask

**Comment by tmdh** [comment]
Go to "View > Toggle Developer Tools" and give me the console errors if there are any.

**Comment by hemant17** [comment]
> Go to "View > Toggle Developer Tools" and give me the console errors if there are any.

C:\Program Files\Laravel Kit\resources\electron.asar\renderer\api\remote.js:209 Uncaught Error: Could not call remote function 'showErrorBox'. Check that the function signature is correct. Underlying error: Error processing argument at index 1, conversion failure from #<Object>
Error: Could not call remote function 'showErrorBox'. Check that the function signature is correct. Underlying error: Error processing argument at index 1, conversion failure from #<Object>
    at callFunction (C:\Program Files\Laravel Kit\resources\electron.asar\browser\rpc-server.js:257:11)
    at EventEmitter.<anonymous> (C:\Program Files\Laravel Kit\resources\electron.asar\browser\rpc-server.js:357:5)
    at emitMany (events.js:146:13)
    at EventEmitter.emit (events.js:223:7)
    at WebContents.<anonymous> (C:\Program Files\Laravel Kit\resources\electron.asar\browser\api\web-contents.js:275:13)
    at emitTwo (events.js:125:13)
    at WebContents.emit (events.js:213:7)
    at callFunction (C:\Program Files\Laravel Kit\resources\electron.asar\browser\rpc-server.js:257:11)
    at EventEmitter.<anonymous> (C:\Program Files\Laravel Kit\resources\electron.asar\browser\rpc-server.js:357:5)
    at emitMany (events.js:146:13)
    at EventEmitter.emit (events.js:223:7)
    at WebContents.<anonymous> (C:\Program Files\Laravel Kit\resources\electron.asar\browser\api\web-contents.js:275:13)
    at emitTwo (events.js:125:13)
    at WebContents.emit (events.js:213:7)
    at Object.exception (C:\Program Files\Laravel Kit\resources\electron.asar\renderer\api\remote.js:209:30)
    at metaToValue (C:\Program Files\Laravel Kit\resources\electron.asar\renderer\api\remote.js:213:28)
    at Object.remoteMemberFunction (C:\Program Files\Laravel Kit\resources\electron.asar\renderer\api\remote.js:113:16)
    at ae (file:///C:/Program%20Files/Laravel%20Kit/resources/app.asar/app/js/index.js:281:9)
    at extract (file:///C:/Program%20Files/Laravel%20Kit/resources/app.asar/app/js/index.js:293:6)
    at C:\Program Files\Laravel Kit\resources\app.asar\node_modules\extract-zip\index.js:31:23
    at C:\Program Files\Laravel Kit\resources\app.asar\node_modules\yauzl\index.js:29:21
    at FSReqWrap.oncomplete (fs.js:135:15)

**Comment by WEBronckhorst** [comment]
I got the same
os: MacOS 11

/Applications/Laravel Kit.app/Contents/Resources/electron.asar/renderer/api/remote.js:209 Uncaught Error: Could not call remote function 'showErrorBox'. Check that the function signature is correct. Underlying error: Error processing argument at index 1, conversion failure from #<Object>
Error: Could not call remote function 'showErrorBox'. Check that the function signature is correct. Underlying error: Error processing argument at index 1, conversion failure from #<Object>
    at callFunction (/Applications/Laravel Kit.app/Contents/Resources/electron.asar/browser/rpc-server.js:257:11)
    at EventEmitter.<anonymous> (/Applications/Laravel Kit.app/Contents/Resources/electron.asar/browser/rpc-server.js:357:5)
    at emitMany (events.js:146:13)
    at EventEmitter.emit (events.js:223:7)
    at WebContents.<anonymous> (/Applications/Laravel Kit.app/Contents/Resources/electron.asar/browser/api/web-contents.js:275:13)
    at emitTwo (events.js:125:13)
    at WebContents.emit (events.js:213:7)
    at callFunction (/Applications/Laravel Kit.app/Contents/Resources/electron.asar/browser/rpc-server.js:257:11)
    at EventEmitter.<anonymous> (/Applications/Laravel Kit.app/Contents/Resources/electron.asar/browser/rpc-server.js:357:5)
    at emitMany (events.js:146:13)
    at EventEmitter.emit (events.js:223:7)
    at WebContents.<anonymous> (/Applications/Laravel Kit.app/Contents/Resources/electron.asar/browser/api/web-contents.js:275:13)
    at emitTwo (events.js:125:13)
    at WebContents.emit (events.js:213:7)
    at Object.exception (/Applications/Laravel Kit.app/Contents/Resources/electron.asar/renderer/api/remote.js:209:30)
    at metaToValue (/Applications/Laravel Kit.app/Contents/Resources/electron.asar/renderer/api/remote.js:213:28)
    at Object.remoteMemberFunction (/Applications/Laravel Kit.app/Contents/Resources/electron.asar/renderer/api/remote.js:113:16)
    at ae (file:///Applications/Laravel%20Kit.app/Contents/Resources/app.asar/app/js/index.js:281:9)
    at extract (file:///Applications/Laravel%20Kit.app/Contents/Resources/app.asar/app/js/index.js:293:6)
    at /Applications/Laravel Kit.app/Contents/Resources/app.asar/node_modules/extract-zip/index.js:31:23
    at /Applications/Laravel Kit.app/Contents/Resources/app.asar/node_modules/yauzl/index.js:29:21
    at FSReqWrap.oncomplete (fs.js:135:15)

**Comment by tmdh** [comment]
I am investigating this issue right now.

**Comment by tmdh** [comment]
This issue is fixed in Laravel Kit [v1.2.4](https://github.com/tmdh/laravel-kit/releases/tag/v1.2.4).
@glensc @hemant17 @WEBronckhorst
