### ISSUE TITLE
How to display errors in Tinker?

### ISSUE THREAD

**Issue by ralphjsmit** [tmdh/laravel-kit#27]
Hey Tareque! 

Thanks for making this application. I really like the concept and especially the Tinker part. It gives me the feeling and conveniences of a text editor instead of the terminal. 

There's one thing that you should absolutely consider building – and that's Tinker error messages. Now, the 'Tinkering...' keeps going, where there's in fact an error message.

Error messages would greatly improve the usefulness of this app and I'd appreciate it if you could consider developing this.

Thanks a lot and have a good weekend!

Ralph

**Comment by tmdh** [comment]
Thanks for your appreciation. Can you check if you can see the errors in 2.0.5?

**Comment by ralphjsmit** [comment]
I downloaded the app again (updating gave an error), but I don't see any output. So I'm not sure whether it was because of a big upgrade or something else. 

To be honest, I've been using Tinkerwell inside PhpStorm for a few months now, so I didn't really use Laravel Kit anymore. It was just easier to see output straight in PhpStorm.

Thanks anyway for still handling the issue!

*Update error (FYI)*
Uncaught Exception:
TypeError: Cannot read property 'toString' of undefined
at u.<anonymous> (/Applications/Laravel Kit.app/Contents/Resources/app.asar/dist/main.js:8:598634)
at u.emit (events.js:327:22)
at AutoUpdater.<anonymous> (/Applications/Laravel Kit.app/Contents/Resources/app.asar/dist/main.js:8:63793)
at AutoUpdater.emit (events.js:315:20)
at Server.<anonymous> (/Applications/Laravel Kit.app/Contents/Resources/app.asar/dist/main.js:8:65810)
at Object.onceWrapper (events.js:421:28)
at Server.emit (events.js:315:20)
at emitListeningNT (net.js:1347:10)
at processTicksAndRejections (internal/process/task_queues.js:83:21)

**Comment by tmdh** [comment]
The macOS app can't auto update itself because it's not code signed and code signing costs 99$/yr.

Anyway, thanks for your feedback.
